=== mariansurdu/xml/PrestareServiciiDomiciliu/PrestareServiciiDomiciliu/bin/Debug/prestare.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.acs.ro/"
xmlns="http://www.acs.ro/"
elementFormDefault="qualified"> 
<xs:element name="planificari">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="planificare" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="tara" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="denumire" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="grupa" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="assignment" maxOccurs="6">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="echipa" maxOccurs="2">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="nume_echipa" type="xs:string"/>
															<xs:element name="membru" maxOccurs="11">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="nume_membru">
																		<xs:simpleType> 
																			 <xs:restriction base="xs:string"> 
																				 <xs:whiteSpace value="preserve"/> 
																			 </xs:restriction> 
																		</xs:simpleType>
																		</xs:element>
																		<xs:element name="serie_ci">
																		<xs:simpleType> 
																			 <xs:restriction base="xs:integer"> 
																				 <xs:minInclusive value="1"/>
																				 <xs:maxInclusive value="90"/> 
																			 </xs:restriction> 
																		</xs:simpleType>
																		</xs:element>
																	    <xs:element name="pozitie">
																		<xs:simpleType>
																			 <xs:restriction base="xs:string"> 
																				<!-- <xs:enumeration value="Portar"/>
																				 <xs:enumeration value="Fundas"/>
																				 <xs:enumeration value="Mijlocas"/> 
																				 <xs:enumeration value="Atacant"/> -->
																			 </xs:restriction>
																		</xs:simpleType>
																		</xs:element>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
															<xs:element name="sofer" minOccurs="1" maxOccurs="1">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="nume_sofer">
																		<xs:simpleType> 
																			 <xs:restriction base="xs:string"> 
																				 <xs:whiteSpace value="preserve"/> 
																			 </xs:restriction> 
																		</xs:simpleType>
																		</xs:element>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="locatie" minOccurs="1" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="adresa" type="xs:string"/>
															<xs:element name="oras" type="xs:string"/>
															<xs:element name="capacitate" type="xs:integer"/>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="persoana_de_contact" minOccurs="1" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="nume_persoana_de_contact">
															<xs:simpleType> 
																<xs:restriction base="xs:string"> 
																	<xs:whiteSpace value="preserve"/> 
																</xs:restriction> 
															</xs:simpleType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="data_assign" minOccurs="1" maxOccurs="1">
													<xs:complexType>
														<xs:attribute name="val" type="xs:string" use="required"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="asg_num" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="Nume_Grupa" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="AN" type="xs:integer" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== mariansurdu/xml/PrestareServiciiDomiciliu/PrestareServiciiDomiciliu/bin/Debug/PrestareServiciiDomiciliu.xml
<?xml version="1.0"?> 
<?xml-stylesheet type="text/xsl" href="E:\XML_GOOD\xml\PrestareServiciiDomiciliu\PrestareServiciiDomiciliu\bin\Debug\prestare.xslt"?>
<!DOCTYPE planificari SYSTEM "prestare.dtd">
<planificari
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="http://www.acs.ro/ prestare.xsd">
	<planificare AN = "2017">
		<tara>
			<denumire>Romania</denumire>
		</tara>
		<grupa Nume_Grupa = "A">
			<assignment asg_num = "1">
				<echipa>
					<nume_echipa>Curatenie1</nume_echipa>
					<membru>
						<nume_membru>Ion Ion</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Menajer</pozitie>
					</membru>
					<membru>
						<nume_membru>Daniel Ion</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Miranda Daniela </nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>David Ionela</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Luiza Simion</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera/Leader</pozitie>
					</membru>
					<membru>
						<nume_membru>Ioana Ion</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>

					<sofer>
						<nume_sofer>Dunga</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Best Cleaning</nume_echipa>
					<membru>
						<nume_membru>Ivan Vargic</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Sime_Vrsaljko</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Goran_Milovic</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Darjo_Srna</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Marko_Leskovic</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Ivan_Perisic</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>
				
					<sofer>
						<nume_sofer>Niko_Kovac</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Republica,Faur 12</adresa>
					<oras>Sao_Paulo</oras>
					<capacitate>46116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Sandra Gheorghe</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "21/03/2017"/>
			</assignment>
			
			<assignment asg_num="2">
				<echipa>
					<nume_echipa>Cleaning safe</nume_echipa>
					<membru>
						<nume_membru>Jose_Corona</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Paul_Aguilar</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Y_Corona </nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>R_Marquez</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Filipe_Luis</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>D_Reyes</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>

					
					<sofer>
						<nume_sofer>Miguel_Herrera</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Cleaning now!</nume_echipa>
					<membru>
						<nume_membru>Charles_Itandje</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Benoit_Assou_Ekotto</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Nicolas_Koulou</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Cedric_Djeugoue</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Dany_Nounkeu</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Jean_Makoun</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>
					<sofer>
						<nume_sofer>Volker_Finke</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Bucuresti Ploiesti 44-46</adresa>
					<oras>Natal</oras>
					<capacitate>46116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Ionut Marian</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "22/04/2017"/>
			</assignment>
			
			<assignment asg_num="3">
				<echipa>
					<nume_echipa>Cleaning good</nume_echipa>
					<membru>
						<nume_membru>Jefferson</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Daniel_Alves</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Miranda </nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>David_Luiz</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Filipe_Luis</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Fernandinho</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>

					
					<sofer>
						<nume_sofer>Dunga</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Cleaning now</nume_echipa>
					<membru>
						<nume_membru> Jose_Corona</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Paul_Aguilar</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Y_Corona </nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>R_Marquez</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Filipe_Luis</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>D_Reyes</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>
					<sofer>
						<nume_sofer>Miguel_Herrera</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Splaiul unirii 32</adresa>
					<oras>Fortaleza</oras>
					<capacitate>46116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Ion Marius</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "21/02/2018"/>
			</assignment>
			<assignment asg_num="4">
				<echipa>
					<nume_echipa>Cleaning now</nume_echipa>
					<membru>
						<nume_membru>Charles_Itandje</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Benoit_Assou_Ekotto</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Nicolas_Koulou</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Cedric_Djeugoue</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Dany_Nounkeu</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Jean_Makoun</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>

					
					<sofer>
						<nume_sofer>Volker_Finke</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Safe clean</nume_echipa>
					<membru>
						<nume_membru>Ivan_Vargic</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Sime_Vrsaljko</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Goran_Milovic</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Darjo_Srna</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Marko_Leskovic</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Ivan_Perisic</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Mijlocas</pozitie>
					</membru>

					<sofer>
						<nume_sofer>Niko_Kovac</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Splaiul unirii 12</adresa>
					<oras>Manaus</oras>
					<capacitate>39116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Gheorghe Ion</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "22/05/2017"/>
			</assignment>
		</grupa>
		
    <grupa Nume_Grupa = "B">
			<assignment asg_num="1">
				<echipa>
					<nume_echipa>Hairdress</nume_echipa>
					<membru>
						<nume_membru>Sergio_Rico</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Portar</pozitie>
					</membru>
					<membru>
						<nume_membru>Sergio_Ramos</nume_membru>
						<serie_ci>15</serie_ci>
						<pozitie>Fundas</pozitie>
					</membru>
					<membru>
						<nume_membru>Gerard_Pique</nume_membru>
						<serie_ci>3</serie_ci>
