=== mariansurdu/xml/CampionatMondialFotbal/CampionatMondialFotbal/bin/Debug/campionate.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.acs.ro/"
xmlns="http://www.acs.ro/"
elementFormDefault="qualified"> 
<xs:element name="campionate">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="campionat" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="tara_gazda" minOccurs="1" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="denumire" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="grupa" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="meci" maxOccurs="6">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="echipa" maxOccurs="2">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="nume_echipa" type="xs:string"/>
															<xs:element name="jucator" maxOccurs="11">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="nume_jucator">
																		<xs:simpleType> 
																			 <xs:restriction base="xs:string"> 
																				 <xs:whiteSpace value="preserve"/> 
																			 </xs:restriction> 
																		</xs:simpleType>
																		</xs:element>
																		<xs:element name="numar">
																		<xs:simpleType> 
																			 <xs:restriction base="xs:integer"> 
																				 <xs:minInclusive value="1"/>
																				 <xs:maxInclusive value="90"/> 
																			 </xs:restriction> 
																		</xs:simpleType>
																		</xs:element>
																	    <xs:element name="pozitie">
																		<xs:simpleType>
																			 <xs:restriction base="xs:string"> 
																				 <xs:enumeration value="Portar"/>
																				 <xs:enumeration value="Fundas"/>
																				 <xs:enumeration value="Mijlocas"/> 
																				 <xs:enumeration value="Atacant"/> 
																			 </xs:restriction>
																		</xs:simpleType>
																		</xs:element>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
															<xs:element name="antrenor" minOccurs="1" maxOccurs="1">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="nume_antrenor">
																		<xs:simpleType> 
																			 <xs:restriction base="xs:string"> 
																				 <xs:whiteSpace value="preserve"/> 
																			 </xs:restriction> 
																		</xs:simpleType>
																		</xs:element>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="stadion" minOccurs="1" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="nume_stadion" type="xs:string"/>
															<xs:element name="oras" type="xs:string"/>
															<xs:element name="capacitate" type="xs:integer"/>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="arbitru" minOccurs="1" maxOccurs="1">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="nume_arbitru">
															<xs:simpleType> 
																<xs:restriction base="xs:string"> 
																	<xs:whiteSpace value="preserve"/> 
																</xs:restriction> 
															</xs:simpleType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="scor" minOccurs="1" maxOccurs="1">
													<xs:complexType>
														<xs:attribute name="val" type="xs:string" use="required"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="Numar_Meci" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="Nume_Grupa" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="AN" type="xs:integer" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== mariansurdu/xml/CampionatMondialFotbal/CampionatMondialFotbal/bin/Debug/Campionat.xml.xml
<?xml version="1.0"?> 
<?xml-stylesheet type="text/xsl" href="E:\FACULTATE AN IV\XML\Proiect\campionat.xslt"?>
<!DOCTYPE campionate SYSTEM "campionat.dtd">
<campionate
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="http://www.acs.ro/ campionate.xsd">
	<campionat AN = "2014">
		<tara_gazda>
			<denumire>Brazilia</denumire>
		</tara_gazda>
		<grupa Nume_Grupa = "A">
			<meci Numar_Meci = "1">
				<echipa>
					<nume_echipa>Brazilia</nume_echipa>
					<jucator>
						<nume_jucator>Jefferson</nume_jucator>
						<numar>1</numar>
						<pozitie>Portar</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Daniel_Alves</nume_jucator>
						<numar>2</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Miranda </nume_jucator>
						<numar>3</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>David_Luiz</nume_jucator>
						<numar>4</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Filipe_Luís</nume_jucator>
						<numar>6</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Fernandinho</nume_jucator>
						<numar>5</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Roberto_Firmino</nume_jucator>
						<numar>11</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Willian</nume_jucator>
						<numar>19</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Philippe_Coutinho</nume_jucator>
						<numar>21</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Neymar</nume_jucator>
						<numar>10</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Robinho</nume_jucator>
						<numar>20</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					
					<antrenor>
						<nume_antrenor>Dunga</nume_antrenor>
					</antrenor>
				</echipa>
				<echipa>
					<nume_echipa>Croatia</nume_echipa>
					<jucator>
						<nume_jucator>Ivan Vargic</nume_jucator>
						<numar>1</numar>
						<pozitie>Portar</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Sime_Vrsaljko</nume_jucator>
						<numar>2</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Goran_Milovic</nume_jucator>
						<numar>3</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Darjo_Srna</nume_jucator>
						<numar>4</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Marko_Leskovic</nume_jucator>
						<numar>6</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Ivan_Perisic</nume_jucator>
						<numar>5</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Ivan_Mocinic</nume_jucator>
						<numar>11</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Marcelo_Brozović</nume_jucator>
						<numar>19</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Milan_Badelj</nume_jucator>
						<numar>21</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Mario_Mandzukic</nume_jucator>
						<numar>10</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Ivica_Olic</nume_jucator>
						<numar>20</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					
					<antrenor>
						<nume_antrenor>Niko_Kovac</nume_antrenor>
					</antrenor>
				</echipa>
				<stadion>
					<nume_stadion>Arena de Sao Paulo</nume_stadion>
					<oras>Sao_Paulo</oras>
					<capacitate>46116</capacitate>
				</stadion>
				<arbitru>
					<nume_arbitru>Sandro_Ricci</nume_arbitru>
				</arbitru>
				<scor val = "3-1"/>
			</meci>
			
			<meci Numar_Meci="2">
				<echipa>
					<nume_echipa>Mexic</nume_echipa>
					<jucator>
						<nume_jucator>Jose_Corona</nume_jucator>
						<numar>1</numar>
						<pozitie>Portar</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Paul_Aguilar</nume_jucator>
						<numar>2</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Y_Corona </nume_jucator>
						<numar>3</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>R_Marquez</nume_jucator>
						<numar>4</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Filipe_Luis</nume_jucator>
						<numar>6</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>D_Reyes</nume_jucator>
						<numar>5</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>J_Aquino</nume_jucator>
						<numar>11</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Ramirez</nume_jucator>
						<numar>19</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Pineda</nume_jucator>
						<numar>21</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Pizarro</nume_jucator>
						<numar>10</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Jimenez</nume_jucator>
						<numar>20</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					
					<antrenor>
						<nume_antrenor>Miguel_Herrera</nume_antrenor>
					</antrenor>
				</echipa>
				<echipa>
					<nume_echipa>Camerun</nume_echipa>
					<jucator>
						<nume_jucator>Charles_Itandje</nume_jucator>
						<numar>1</numar>
						<pozitie>Portar</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Benoit_Assou_Ekotto</nume_jucator>
						<numar>2</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Nicolas_Koulou</nume_jucator>
						<numar>3</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Cedric_Djeugoue</nume_jucator>
						<numar>4</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Dany_Nounkeu</nume_jucator>
						<numar>6</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Jean_Makoun</nume_jucator>
						<numar>5</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Eyong_Enoh</nume_jucator>
						<numar>11</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Edgar_Salli</nume_jucator>
						<numar>19</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Joel_Matip</nume_jucator>
						<numar>21</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Benjamin_Moukandjo</nume_jucator>
						<numar>10</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Pierre_Webo</nume_jucator>
						<numar>20</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					
					<antrenor>
						<nume_antrenor>Volker_Finke</nume_antrenor>
					</antrenor>
				</echipa>
				<stadion>
					<nume_stadion>Arena_das_Dunas</nume_stadion>
					<oras>Natal</oras>
					<capacitate>46116</capacitate>
				</stadion>
				<arbitru>
					<nume_arbitru>Wilmar_Roldán</nume_arbitru>
				</arbitru>
				<scor val = "1-0"/>
			</meci>
			
			<meci Numar_Meci="3">
				<echipa>
					<nume_echipa>Brazilia</nume_echipa>
					<jucator>
						<nume_jucator>Jefferson</nume_jucator>
						<numar>1</numar>
						<pozitie>Portar</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Daniel_Alves</nume_jucator>
						<numar>2</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Miranda </nume_jucator>
						<numar>3</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>David_Luiz</nume_jucator>
						<numar>4</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Filipe_Luis</nume_jucator>
						<numar>6</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Fernandinho</nume_jucator>
						<numar>5</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Roberto_Firmino</nume_jucator>
						<numar>11</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Willian</nume_jucator>
						<numar>19</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Philippe_Coutinho</nume_jucator>
						<numar>21</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Neymar</nume_jucator>
						<numar>10</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Robinho</nume_jucator>
						<numar>20</numar>
						<pozitie>Atacant</pozitie>
					</jucator>
					
					<antrenor>
						<nume_antrenor>Dunga</nume_antrenor>
					</antrenor>
				</echipa>
				<echipa>
					<nume_echipa>Mexic</nume_echipa>
					<jucator>
						<nume_jucator> Jose_Corona</nume_jucator>
						<numar>1</numar>
						<pozitie>Portar</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Paul_Aguilar</nume_jucator>
						<numar>2</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Y_Corona </nume_jucator>
						<numar>3</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>R_Marquez</nume_jucator>
						<numar>4</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>Filipe_Luis</nume_jucator>
						<numar>6</numar>
						<pozitie>Fundas</pozitie>
					</jucator>
					<jucator>
						<nume_jucator>D_Reyes</nume_jucator>
						<numar>5</numar>
						<pozitie>Mijlocas</pozitie>
					</jucator>
