=== mariansurdu/xml/PrestareServiciiDomiciliu/fisiere xml/prestare.dtd
<!ELEMENT planificari (planificare+)>
<!ATTLIST planificare AN CDATA #REQUIRED>
<!ELEMENT planificare (tara,grupa+)>
<!ELEMENT tara (denumire)>
<!ELEMENT denumire (#PCDATA)>
<!ATTLIST grupa Nume_Grupa CDATA #REQUIRED>
<!ELEMENT grupa (assignment+)>  
<!ATTLIST assignment asg_num CDATA #REQUIRED> 
<!ELEMENT assignment (echipa+,locatie,persoana_de_contact,data_assign)>
<!ELEMENT echipa (nume_echipa,membru+,sofer)>
<!ELEMENT nume_echipa (#PCDATA)>
<!ELEMENT membru (nume_membru,serie_ci,pozitie)>
<!ELEMENT nume_membru (#PCDATA)>
<!ELEMENT serie_ci (#PCDATA)>
<!ELEMENT pozitie (#PCDATA)>
<!ELEMENT sofer (nume_sofer)>
<!ELEMENT nume_sofer (#PCDATA)>
<!ELEMENT locatie (adresa,oras,capacitate)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT oras (#PCDATA)>
<!ELEMENT capacitate (#PCDATA)>
<!ELEMENT persoana_de_contact (nume_persoana_de_contact)>
<!ELEMENT nume_persoana_de_contact (#PCDATA)>
<!ELEMENT data_assign EMPTY> 
<!ATTLIST data_assign val CDATA #REQUIRED>

=== mariansurdu/xml/PrestareServiciiDomiciliu/fisiere xml/PrestareServiciiDomiciliu.xml
<?xml version="1.0"?> 
<?xml-stylesheet type="text/xsl" href="E:\XML_GOOD\xml\PrestareServiciiDomiciliu\PrestareServiciiDomiciliu\bin\Debug\prestare.xslt"?>
<!DOCTYPE planificari SYSTEM "prestare.dtd">
<planificari
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="http://www.acs.ro/ prestare.xsd">
	<planificare AN = "2017">
		<tara>
			<denumire>Romania</denumire>
		</tara>
		<grupa Nume_Grupa = "A">
			<assignment asg_num = "1">
				<echipa>
					<nume_echipa>Curatenie1</nume_echipa>
					<membru>
						<nume_membru>Andreea Alexe</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Maria Burciu</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Raluca Cristea</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Andrei Badea</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Alexandru Matache</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Antoneta Sandu</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>

					<sofer>
						<nume_sofer>Doru Aldea</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Best Cleaning</nume_echipa>
					<membru>
						<nume_membru>Matei Basarab</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Cristi Ciurea</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Mihaela Dublea</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>
					<membru>
						<nume_membru>Marius Ragu</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Madalina Culea</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Bogdan Iurie</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Responsabil Piscina</pozitie>
					</membru>
				
					<sofer>
						<nume_sofer>Paul Androne</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Republica,Faur 12</adresa>
					<oras>Bucuresti</oras>
					<capacitate>46116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Adriana Rusu</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "21/03/2017"/>
			</assignment>
			
			<assignment asg_num="2">
				<echipa>
					<nume_echipa>Cleaning safe</nume_echipa>
					<membru>
						<nume_membru>Robert Martinescu</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Marta Dobre</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>
					<membru>
						<nume_membru>Berta Craciunescu</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Martin Nita</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Carla Visinoiu</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Paula Umgureanu</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>

					
					<sofer>
						<nume_sofer>Rebeca Dumitru</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Cleaning now!</nume_echipa>
					<membru>
						<nume_membru>Paul Vis</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Stanca Perdun</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Valentina Iuga</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Radu Beluciu</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>
					<membru>
						<nume_membru>Daniela Robu</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Nicoleta Nuta</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<sofer>
						<nume_sofer>Carmen Voinea</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Bucuresti Ploiesti 44-46</adresa>
					<oras>Bucuresti</oras>
					<capacitate>46116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Eugen Popa</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "22/04/2017"/>
			</assignment>
			
			<assignment asg_num="3">
				<echipa>
					<nume_echipa>Cleaning good</nume_echipa>
					<membru>
						<nume_membru>Andrei Onofrei</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Daniel Rusu</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Miruna Ducu </nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Andra Bega</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>
					<membru>
						<nume_membru>Cristina Eremia</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Francisca Grigore</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>

					
					<sofer>
						<nume_sofer>Matei Ursu</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Cleaning now</nume_echipa>
					<membru>
						<nume_membru>Marius Sofron</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Grigore Albu</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Irina Mutu</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Carolina Mugur</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>
					<membru>
						<nume_membru>Filip Andrei</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Raluca Vlad</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<sofer>
						<nume_sofer>Diana Tudor</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Splaiul unirii 32</adresa>
					<oras>Cluj</oras>
					<capacitate>46116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Ana Ciucure</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "21/02/2018"/>
			</assignment>
			<assignment asg_num="4">
				<echipa>
					<nume_echipa>Cleaning now</nume_echipa>
					<membru>
						<nume_membru>Indrie Anton</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Alexandru Chirita</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Responsabil Piscina</pozitie>
					</membru>
					<membru>
						<nume_membru>Andreea Niculescu</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Marcela Iancu</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Adriana Dan</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Cristina Rosu</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>

					
					<sofer>
						<nume_sofer>Darius Visan</nume_sofer>
					</sofer>
				</echipa>
				<echipa>
					<nume_echipa>Safe clean</nume_echipa>
					<membru>
						<nume_membru>Andi Marculescu</nume_membru>
						<serie_ci>1</serie_ci>
						<pozitie>Responsabil Echipa</pozitie>
					</membru>
					<membru>
						<nume_membru>Adriana Marcu</nume_membru>
						<serie_ci>2</serie_ci>
						<pozitie>Calcat Rufe</pozitie>
					</membru>
					<membru>
						<nume_membru>Andreea Bucur</nume_membru>
						<serie_ci>3</serie_ci>
						<pozitie>Gradinar</pozitie>
					</membru>
					<membru>
						<nume_membru>Laura Toma</nume_membru>
						<serie_ci>4</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Florentina Raicu</nume_membru>
						<serie_ci>6</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>
					<membru>
						<nume_membru>Paula Ivan</nume_membru>
						<serie_ci>5</serie_ci>
						<pozitie>Menajera</pozitie>
					</membru>

					<sofer>
						<nume_sofer>Vlad Dumitru</nume_sofer>
					</sofer>
				</echipa>
				<locatie>
					<adresa>Splaiul unirii 12</adresa>
					<oras>Timisoara</oras>
					<capacitate>39116</capacitate>
				</locatie>
				<persoana_de_contact>
					<nume_persoana_de_contact>Ariana Bratu</nume_persoana_de_contact>
				</persoana_de_contact>
				<data_assign val = "22/05/2017"/>
			</assignment>
		</grupa>
		
    <grupa Nume_Grupa = "B">
			<assignment asg_num="1">
				<echipa>
					<nume_echipa>Hairdress</nume_echipa>
					<membru>
						<nume_membru>Dan-Petre Vlad</nume_membru>
						<serie_ci>1</serie_ci>
